---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vms
resources:
  - ./k3s-prod-1-worker-1.yaml
  # - ./k3s-prod-1-worker-2.yaml
  - ./k3s-prod-1-worker-3.yaml

patches:
  # add podAntiAffinity to all worker nodes
  - path: ./common-patch.yaml
    target:
      group: kubevirt.io
      kind: VirtualMachine
